#!/bin/bash

OPTIND=1

version=1

while getopts "v" opt; do
  case "$opt" in
    v)  version=1
      ;;
  esac
done

shift $((OPTIND-1))

gradleArg="$@"

if [ $version == 1 ]; then
	sed "s/§§.*§§/§§$(date +%y-%m-%d_%H:%M:%S) $(hostname)§§/" app/src/main/kotlin/com/femtioprocent/omega/OmegaVersion.kt > Z-OmegaVersion.kt
	mv Z-OmegaVersion.kt  app/src/main/kotlin/com/femtioprocent/omega/OmegaVersion.kt
fi

./gradlew $gradleArg

mkdir -p runtime/lib
mkdir -p runtime/omega_assets
rsync --delete -uvarHl app/build/install/app/lib/ runtime/lib
