#!/bin/bash

echo pwd 1: $(pwd)

jx=$(which java)

cd $(dirname $0)

echo pwd 2: $(pwd)

$jx -version

ls default.omega_assets && $jx -cp "lib/*" com.femtioprocent.omega.appl.Omega_IS "$@" || ./selectOmegaAssets
