/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.1.1/userguide/building_java_projects.html
 */

plugins {
    java
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
//    kotlin("jvm") version "2.1.20"
    id("org.jetbrains.kotlin.jvm") version "2.1.20"
    id("io.gitlab.arturbosch.detekt") version "1.23.8"
}

tasks.register<Wrapper>("wrapper") {
    gradleVersion = "8.14"
    distributionType = Wrapper.DistributionType.ALL
}

tasks.register("prepareKotlinBuildScriptModel") {
}

tasks.named<Jar>("jar") {
//    dependsOn("copyToLibs")
    manifest {
        attributes["Main-Class"] = "com.femtioprocent.omega.appl.Omega_IS"
//        attributes["Class-Path"] = configurations.compileClasspath.joinToString(separator = " ") { it.name }
    }
}

javafx {
    version = "20"
    modules("javafx.controls", "javafx.fxml", "javafx.swing", "javafx.media", "javafx.graphics")
}

detekt {
    files("config/detekt/detekt.yaml")
    toolVersion = "1.23.8"
    ignoreFailures = true
}

repositories {
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
    implementation("de.codecentric.centerdevice:centerdevice-nsmenufx:2.1.4")
    implementation("com.intellij:forms_rt:7.0.3")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("io.arrow-kt:arrow-core:1.2.0")
    implementation("io.arrow-kt:arrow-fx-coroutines:1.2.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "com.femtioprocent.omega.appl.Omega_IS"
    executableDir = "../runtime"
}

/* +
compileKotlin {
}

compileTestKotlin {
}
*/
