naming:
  VariableNaming:
    variablePattern: '[a-z][A-Za-z0-9_]*'
  FunctionParameterNaming:
    variablePattern: '[a-z][A-Za-z0-9_]*'
  ConstructorParameterNaming:
    variablePattern: '[a-z][A-Za-z0-9_]*'