naming:
  VariableNaming:
    variablePattern: '[a-z][A-Za-z0-9_]*'
  FunctionParameterNaming:
    parameterPattern: '[a-z][A-Za-z0-9_]*'
  FunctionNaming:
    functionPattern: '[a-z][A-Za-z0-9_]*'
  ConstructorParameterNaming:
    parameterPattern: '[a-z][A-Za-z0-9_]*'
