naming:
  VariableNaming:
    variablePattern: '[a-z][A-Za-z0-9_]*'
  FunctionParameterNaming:
    parameterPattern: '[a-z][A-Za-z0-9_]*'
  FunctionNaming:
    functionPattern: '[a-z][A-Za-z0-9_]*'
  ConstructorParameterNaming:
    parameterPattern: '[a-z][A-Za-z0-9_]*'
  ObjectPropertyNaming:
    propertyPattern: '[a-z][A-Za-z0-9_]*'
style:
  MagicNumber:
    ignoreNumbers:
      "-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9"
complexity:
  LongParameterList:
    constructorThreshold: 10
    functionThreshold: 10
console-reports:
  active: true
  exclude:
  #  - 'ProjectStatisticsReport'
  #  - 'ComplexityReport'
  #  - 'NotificationReport'
  #  - 'FindingsReport'
  #  - 'FileBasedFindingsReport'
  #  - 'LiteFindingsReport'
  output-reports:
    active: true
    exclude:
      - 'TxtOutputReport'
      - 'XmlOutputReport'
      - 'SarifOutputReport'
  #  - 'HtmlOutputReport'
