/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.femtioprocent.omega

import org.junit.Assert
import org.junit.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
	val classUnderTest = App()
	Assert.assertNotNull("app should have a greeting", classUnderTest.greeting)
    }
}
