/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.femtioprocent.omega

class App {
    val greeting: String
	get() = "Hello World!"

    companion object {
	@JvmStatic
	fun main(args: Array<String>) {
	    println(App().greeting)
	}
    }
}
